version: '3'
services:
  backend:
    image: patlytics/backend:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      PT_APP_HOST: "0.0.0.0"
      PT_APP_PORT: 8000
      PT_APP_WORKERS: 1
      PT_GPT_GROQ_API_KEY: your-api-key
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: patlytics-2024
      DB_USER: patlytics-2024
      DB_PASSWORD: patlytics-2024
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: patlytics/frontend:latest
    restart: always
    ports:
      - "3000:3000"

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: patlytics-2024
      POSTGRES_USER: patlytics-2024
      POSTGRES_PASSWORD: patlytics-2024
    volumes:
      - './storage/db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 60s
      retries: 10
