"""add created_at and updated_at

Revision ID: 1d8b8414fb6f
Revises: e3df66db1e0b
Create Date: 2024-11-03 14:59:45.083097

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d8b8414fb6f"
down_revision: Union[str, None] = "e3df66db1e0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assess_infringement", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "assess_infringement", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assess_infringement", "updated_at")
    op.drop_column("assess_infringement", "created_at")
    # ### end Alembic commands ###
