"""Create a baseline migrations 2

Revision ID: e3df66db1e0b
Revises: 17882e76f85d
Create Date: 2024-11-03 09:13:59.253574

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3df66db1e0b"
down_revision: Union[str, None] = "17882e76f85d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assess_infringement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patent_id", sa.String(), nullable=True),
        sa.Column("company_name", sa.String(), nullable=True),
        sa.Column("analysis_date", sa.DateTime(), nullable=True),
        sa.Column("top_infringing_products", sa.JSON(), nullable=True),
        sa.Column("overall_risk_assessment", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("assess_infringement")
    # ### end Alembic commands ###
